export const dummyFeatures = [
  {
    id: '1',
    name: 'User Authentication System',
    description: 'Complete user login, registration, and password reset functionality',
    status: 'completed',
    priority: 'high',
    storyPoints: 13,
    assignedTo: 'John Doe',
    sprint: 'Sprint 1',
    progress: 100,
    startDate: '2024-01-15',
    endDate: '2024-01-28',
    dependencies: ['Database Setup'],
    tags: ['Authentication', 'Security']
  },
  {
    id: '2',
    name: 'Dashboard Development',
    description: 'Main dashboard with analytics and key metrics display',
    status: 'progress',
    priority: 'high',
    storyPoints: 21,
    assignedTo: 'Jane Smith',
    sprint: 'Sprint 2',
    progress: 65,
    startDate: '2024-01-29',
    endDate: '2024-02-11',
    dependencies: ['User Authentication System'],
    tags: ['UI/UX', 'Analytics']
  },
  {
    id: '3',
    name: 'API Integration',
    description: 'Integration with third-party APIs for data synchronization',
    status: 'progress',
    priority: 'medium',
    storyPoints: 8,
    assignedTo: 'Mike Johnson',
    sprint: 'Sprint 2',
    progress: 30,
    startDate: '2024-02-01',
    endDate: '2024-02-08',
    dependencies: [],
    tags: ['API', 'Integration']
  },
  {
    id: '4',
    name: 'Database Optimization',
    description: 'Optimize database queries and implement caching',
    status: 'new',
    priority: 'medium',
    storyPoints: 5,
    assignedTo: 'Sarah Wilson',
    sprint: 'Sprint 3',
    progress: 0,
    startDate: '2024-02-12',
    endDate: '2024-02-19',
    dependencies: ['API Integration'],
    tags: ['Database', 'Performance']
  },
  {
    id: '5',
    name: 'Mobile Responsiveness',
    description: 'Ensure all pages are mobile-friendly and responsive',
    status: 'blocked',
    priority: 'high',
    storyPoints: 13,
    assignedTo: 'Alex Brown',
    sprint: 'Sprint 3',
    progress: 10,
    startDate: '2024-02-12',
    endDate: '2024-02-25',
    dependencies: ['Dashboard Development'],
    tags: ['Mobile', 'Responsive']
  },
  {
    id: '6',
    name: 'Payment Gateway',
    description: 'Integrate payment processing with Stripe',
    status: 'new',
    priority: 'high',
    storyPoints: 21,
    assignedTo: 'Chris Davis',
    sprint: 'Sprint 4',
    progress: 0,
    startDate: '2024-02-26',
    endDate: '2024-03-11',
    dependencies: ['User Authentication System'],
    tags: ['Payment', 'Integration']
  },
  {
    id: '7',
    name: 'Admin Panel',
    description: 'Administrative interface for user and content management',
    status: 'new',
    priority: 'medium',
    storyPoints: 34,
    assignedTo: 'Emma Taylor',
    sprint: 'Sprint 4',
    progress: 0,
    startDate: '2024-03-01',
    endDate: '2024-03-18',
    dependencies: ['Dashboard Development'],
    tags: ['Admin', 'Management']
  },
  {
    id: '8',
    name: 'Reporting System',
    description: 'Generate and export various business reports',
    status: 'new',
    priority: 'low',
    storyPoints: 13,
    assignedTo: 'David Lee',
    sprint: 'Sprint 5',
    progress: 0,
    startDate: '2024-03-19',
    endDate: '2024-04-01',
    dependencies: ['Admin Panel'],
    tags: ['Reports', 'Analytics']
  }
];

export const dummyProjects = [
  {
    id: 'proj-1',
    name: 'E-commerce Platform',
    description: 'Complete online shopping platform with payment integration',
    totalFeatures: 8,
    completedFeatures: 1,
    totalStoryPoints: 128,
    completedStoryPoints: 13,
    estimatedSprints: 5,
    currentSprint: 2,
    startDate: '2024-01-15',
    endDate: '2024-04-01',
    teamSize: 6,
    riskLevel: 'medium'
  }
];